<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\AutoSpareParts.Domain\AutoSpareParts.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Endpoints\DTOs\" />
      <Folder Include="Features\UserAccounts\CustomerAccounts\BusinessRules\" />
      <Folder Include="Features\UserAccounts\CustomerAccounts\Commands\" />
      <Folder Include="Features\UserAccounts\CustomerAccounts\Constants\" />
      <Folder Include="Features\UserAccounts\CustomerAccounts\Queries\" />
      <Folder Include="Features\UserAccounts\CustomerAccounts\Validations\" />
      <Folder Include="Features\UserAccounts\EmployeeAccounts\BusinessRules" />
      <Folder Include="Features\Addresses\Commands\" />
      <Folder Include="Features\EmployeeAddresses\BusinessRules" />
      <Folder Include="Features\EmployeeAddresses\Models\ViewModels" />
      <Folder Include="Features\Endpoints\BusinessRules" />
      <Folder Include="Features\Endpoints\MappingProfiles" />
      <Folder Include="Features\Endpoints\Validations" />
      <Folder Include="Features\IPAddresses\BusinessRules\" />
      <Folder Include="Features\MainCategories\BusinessRules\" />
      <Folder Include="Features\Roles\BusinessRules" />
      <Folder Include="Features\EmployeeImages\BusinessRules" />
      <Folder Include="Features\EmployeeImages\Models\ViewModels" />
      <Folder Include="Features\Employees\BusinessRules" />
      <Folder Include="Helpers" />
      <Folder Include="Models\ViewModels" />
      <Folder Include="Validations" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="13.0.1" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
      <PackageReference Include="IPAddressRange" Version="6.0.0" />
      <PackageReference Include="MediatR" Version="12.4.1" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.1.3" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
    </ItemGroup>

</Project>
